services:
  oso:
    build:
      context: oso
      dockerfile: Dockerfile
    environment:
      - OSO_AUTH=e_0123456789_12345_osotesttoken01xiIn
      - OSO_URL=http://localhost:8081
    ports:
      - 8081:8081
    volumes:
      - ./oso/data:/data
      - ./oso/policy:/policy

  postgres:
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=oso
      - POSTGRES_DB=app_db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build:
      dockerfile: AppDockerfile
    environment:
      - DATABASE_URL=postgresql://oso:password@postgres:5432/app_db
      - OSO_AUTH=e_0123456789_12345_osotesttoken01xiIn
      - OSO_URL=http://oso:8081
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_APP=app.py
    ports:
      - 5050:5050
    depends_on:
      - postgres
      - oso
