services:
  oso:
    image: public.ecr.aws/osohq/dev-server:latest
    command: dev --watch-for-changes /policy/policy.polar
    environment:
      - OSO_AUTH=e_0123456789_12345_osotesttoken01xiIn
      - OSO_URL=http://localhost:8081
      - OSO_DIRECTORY=/data
      - OSO_PORT=8081
      - OSO_FEATURES=reconcile-facts-update
    ports:
      - 8081:8081
    tty: true
    stdin_open: true
    volumes:
      - ./oso/data:/data
      - ./oso/policy:/policy

  postgres:
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=oso
      - POSTGRES_DB=app_db
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build:
      dockerfile: AppDockerfile
    environment:
      - DATABASE_URL=postgresql://oso:password@postgres:5432/app_db
      - OSO_AUTH=e_0123456789_12345_osotesttoken01xiIn
      - OSO_URL=http://oso:8081
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_APP=app.py
    ports:
      - 5050:5050
    depends_on:
      - postgres
      - oso
